server:
  port: 8082

spring:
  config:
    import: "configserver:http://configserver:8080"
  data:
    mongodb:
      uri: mongodb://mongodb:27017/fitnessactivity
      database: fitnessactivity

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://servicereg:8761/eureka/

rabbitmq:
  exchange:
    name: fitness.exchange
  queue:
    name: activity.queue
  routing:
    key: activity.tracking
